name: 'Install Dependencies'
description: 'Installs dependencies defined in package.json'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v6
    - uses: pnpm/action-setup@v6
      with:
        version: 10.33.0
    - uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
    - name: Validate versions
      run: |
        echo "Node version: $(node -v)"
        echo "PNPM version: $(pnpm -v)"
      shell: bash
