import { View } from 'thunderous-csr';
import { BlockQuote } from './components/block-quote';
import { Code, CodeBlock } from './components/code';
import { ContentGroup } from './components/content-group';
import { DocPage } from './components/doc-page';
import { ErrorMessage } from './components/error-message';
import { Footer } from './components/footer';
import { ContentHeader, PageHeader, SubHeader } from './components/header';
import { Heading } from './components/heading';
import { Icon } from './components/icon';
import { InvisibleLink, Link, LinkButton } from './components/link';
import { MarketingContent } from './components/marketing-content';
import { Page } from './components/page';
import { Splash } from './components/splash';
import { Table, TableBody, TableCell, TableHeader, TableHeaderSection, TableRow } from './components/table';
import { Text } from './components/text';

View.define('t-view');
Page.define('th-page');
DocPage.define('th-doc-page');
Splash.define('th-splash');
Link.define('th-link');
InvisibleLink.define('th-invisible-link');
LinkButton.define('th-link-button');
PageHeader.define('th-page-header');
ContentHeader.define('th-content-header');
SubHeader.define('th-sub-header');
Text.define('th-text');
ContentGroup.define('th-content-group');
Code.define('th-code');
CodeBlock.define('th-code-block');
BlockQuote.define('th-block-quote');
Icon.define('th-icon');
Footer.define('th-footer');
ErrorMessage.define('th-error-message');
MarketingContent.define('th-marketing-content');
Heading.define('th-heading');
Table.define('th-table');
TableRow.define('th-tr');
TableHeader.define('th-th');
TableCell.define('th-td');
TableBody.define('th-tbody');
TableHeaderSection.define('th-thead');
